# Generated by Django 3.1.2 on 2020-10-18 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='plane',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservation.plane'),
        ),
    ]
