# Generated by Django 3.1.2 on 2020-10-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20201026_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='column',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.IntegerField(default=1),
        ),
    ]
